[project]
name = "dbt-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dbt-core>=1.10.17",
    "dbt-databricks>=1.10.9",
]
